---
channel: stable
addons:
  victoria-metrics:
    repository: QuentinBtd/hassio-addon-victoria-metrics
    target: victoria-metrics
    # image: ghcr.io/QuentinBtd/hassio-addon-victoria-metrics/{arch}
